# Generated by Django 3.0.6 on 2020-05-17 21:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200517_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime_released',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 21, 51, 42, 449511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 21, 51, 42, 449511, tzinfo=utc)), verbose_name='Fecha de publicación'),
        ),
    ]
