# Generated by Django 3.0.6 on 2020-05-17 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200517_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime_released',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 21, 52, 20, 967219, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
